name: Print Name and Designation

on: push

jobs:
  print-info:
    runs-on: ubuntu-latest
    steps:
      - name: Print Name
        run: echo "Name: Shameel Ahmad"
      
      - name: Print Designation
        run: echo "Designation: Junior Software Engineer"
